import { Routes } from '@angular/router';
import { seoResolver } from './core/resolvers/seo.resolver';

/** Every static page declares a `seoKey`; it maps to a page entry in super admin. */
const seo = (seoKey: string) => ({
  data: { seoKey },
  resolve: { seo: seoResolver },
});

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./layouts/main-layout/main-layout').then(m => m.MainLayout),
    children: [
      {
        path: '',
        ...seo('home'),
        loadComponent: () => import('./pages/home/index/index').then(m => m.Index)
      },
      {
        path: 'about',
        ...seo('about'),
        loadComponent: () => import('./pages/about-us/index/index').then(m => m.Index)
      },
      {
        path: 'team',
        ...seo('team'),
        loadComponent: () => import('./pages/team/index/index').then(m => m.Index)
      },
      {
        // The HTML sitemap for humans. The machine-readable one is the static
        // public/sitemap.xml, generated by scripts/generate-sitemap.mjs.
        path: 'sitemap',
        ...seo('sitemap'),
        loadComponent: () => import('./pages/sitemap/sitemap').then(m => m.Sitemap)
      },
      {
        path: 'support',
        loadComponent: () => import('./pages/support/support.component').then(m => m.SupportComponent),
        children: [
          { path: '', ...seo('support'), loadComponent: () => import('./pages/support/support-center/support-center').then(m => m.SupportCenter) },
          { path: 'privacy-policy', ...seo('support/privacy-policy'), loadComponent: () => import('./pages/support/privacy-policy/privacy-policy').then(m => m.PrivacyPolicy) },
          { path: 'terms-of-service', ...seo('support/terms-of-service'), loadComponent: () => import('./pages/support/terms-of-service/terms-of-service').then(m => m.TermsOfService) },
          { path: 'cookie-policy', ...seo('support/cookie-policy'), loadComponent: () => import('./pages/support/cookie-policy/cookie-policy').then(m => m.CookiePolicy) },
          { path: 'refund-policy', ...seo('support/refund-policy'), loadComponent: () => import('./pages/support/refund-policy/refund-policy').then(m => m.RefundPolicy) },
          { path: 'beta-policy', ...seo('support/beta-policy'), loadComponent: () => import('./pages/support/beta-policy/beta-policy').then(m => m.BetaPolicy) },
          { path: 'faq', ...seo('support/faq'), loadComponent: () => import('./pages/support/faq/faq').then(m => m.Faq) },
          { path: 'data-deletion', ...seo('support/data-deletion'), loadComponent: () => import('./pages/support/data-deletion/data-deletion').then(m => m.DataDeletion) },
          { path: 'delete-your-account', ...seo('support/delete-your-account'), loadComponent: () => import('./pages/support/delete-your-account/delete-your-account').then(m => m.DeleteYourAccount) },
          { path: 'disclosure-policy', ...seo('support/disclosure-policy'), loadComponent: () => import('./pages/support/disclosure-policy/disclosure-policy').then(m => m.DisclosurePolicy) },
          { path: 'system-status', ...seo('support/system-status'), loadComponent: () => import('./pages/support/system-status/system-status').then(m => m.SystemStatus) },
          { path: 'website-terms', ...seo('support/website-terms'), loadComponent: () => import('./pages/support/website-terms/website-terms').then(m => m.WebsiteTerms) },
          { path: 'do-not-sell', ...seo('support/do-not-sell'), loadComponent: () => import('./pages/support/do-not-sell/do-not-sell').then(m => m.DoNotSell) },
          { path: 'change-log', ...seo('support/change-log'), loadComponent: () => import('./pages/support/change-log/change-log').then(m => m.ChangeLog) },
          { path: 'community', ...seo('support/community'), loadComponent: () => import('./pages/support/community/community').then(m => m.Community) },
          { path: 'report-abuse', ...seo('support/report-abuse'), loadComponent: () => import('./pages/support/report-abuse/report-abuse').then(m => m.ReportAbuse) },
          { path: 'tutorials', ...seo('support/tutorials'), loadComponent: () => import('./pages/support/tutorials/tutorials').then(m => m.Tutorials) },
          // Detail page  meta comes from the record itself, set in the component.
          { path: 'tutorials/:id', loadComponent: () => import('./pages/support/tutorials/tutorial-details/tutorial-details').then(m => m.TutorialDetails) },
          { path: 'expert-sessions', ...seo('support/expert-sessions'), loadComponent: () => import('./pages/support/expert-sessions/expert-sessions').then(m => m.ExpertSessions) },
          { path: 'feature-request', ...seo('support/feature-request'), loadComponent: () => import('./pages/support/feature-request/feature-request').then(m => m.FeatureRequest) }
        ]
      },
      {
        path: 'company',
        loadComponent: () => import('./pages/company/company.component').then(m => m.CompanyComponent),
        children: [
          { path: '', redirectTo: 'customer-stories', pathMatch: 'full' },
          { path: 'customer-stories', ...seo('company/customer-stories'), loadComponent: () => import('./pages/company/customer-stories/customer-stories').then(m => m.CustomerStories) },
          { path: 'careers', ...seo('company/careers'), loadComponent: () => import('./pages/company/careers/careers').then(m => m.Careers) },
          { path: 'newsroom', ...seo('company/newsroom'), loadComponent: () => import('./pages/company/newsroom/newsroom').then(m => m.Newsroom) },
          // Detail page  meta comes from the record itself, set in the component.
          { path: 'newsroom/:slug', loadComponent: () => import('./pages/company/newsroom/news-details/news-details').then(m => m.NewsDetails) },
          { path: 'trust-center', ...seo('company/trust-center'), loadComponent: () => import('./pages/company/trust-center/trust-center').then(m => m.TrustCenter) }
        ]
      },
      {
        path: 'modules',
        loadComponent: () => import('./pages/modules/modules.component').then(m => m.ModulesComponent),
        children: [
          { path: 'social-media-management', ...seo('modules/social-media-management'), loadComponent: () => import('./pages/modules/social-media-management/index/index').then(m => m.Index) },
          { path: 'project-management', ...seo('modules/project-management'), loadComponent: () => import('./pages/modules/project-mangement/project-mangement').then(m => m.ProjectMangement) },
          { path: 'token-management', ...seo('modules/token-management'), loadComponent: () => import('./pages/modules/token-management/token-management').then(m => m.TokenManagement) },
          { path: 'employee-management', ...seo('modules/employee-management'), loadComponent: () => import('./pages/modules/employee-management/employee-management').then(m => m.EmployeeManagement) },
          { path: 'finance-accounting', ...seo('modules/finance-accounting'), loadComponent: () => import('./pages/modules/finance-accounting/finance-accounting').then(m => m.FinanceAccounting) },
          { path: 'hrms', ...seo('modules/hrms'), loadComponent: () => import('./pages/modules/hrms/hrms').then(m => m.Hrms) },
          { path: 'crm', ...seo('modules/crm'), loadComponent: () => import('./pages/modules/crm/crm').then(m => m.Crm) },
          { path: 'payroll', ...seo('modules/payroll'), loadComponent: () => import('./pages/modules/payroll/payroll').then(m => m.Payroll) },
          { path: 'influencer-management', ...seo('modules/influencer-management'), loadComponent: () => import('./pages/modules/influencer-management/influencer-management').then(m => m.InfluencerManagement) },
          { path: 'it-management', ...seo('modules/it-management'), loadComponent: () => import('./pages/modules/it-management/it-management').then(m => m.ItManagement) },
          { path: 'bills-utility', ...seo('modules/bills-utility'), loadComponent: () => import('./pages/modules/bills-utility/bills-utility').then(m => m.BillsUtility) },
          { path: 'seo', ...seo('modules/seo'), loadComponent: () => import('./pages/modules/seo/seo').then(m => m.Seo) },
          { path: 'attendance', ...seo('modules/attendance'), loadComponent: () => import('./pages/modules/attendance/attendance').then(m => m.Attendance) },
          { path: 'cloud-storage', ...seo('modules/cloud-storage'), loadComponent: () => import('./pages/modules/cloud-storage/cloud-storage').then(m => m.CloudStorage) },
          { path: 'reports-analytics', ...seo('modules/reports-analytics'), loadComponent: () => import('./pages/modules/reports-analytics/reports-analytics').then(m => m.ReportsAnalytics) }
        ]
      },
      {
        path: 'solutions',
        loadComponent: () => import('./pages/solutions/solutions.component').then(m => m.SolutionsComponent),
        children: [
          { path: '', redirectTo: 'enterprise', pathMatch: 'full' },
          { path: 'enterprise', ...seo('solutions/enterprise'), loadComponent: () => import('./pages/solutions/enterprise/enterprise').then(m => m.Enterprise) },
          { path: 'agencies', ...seo('solutions/agencies'), loadComponent: () => import('./pages/solutions/agencies/agencies').then(m => m.Agencies) },
          { path: 'small-medium-business', ...seo('solutions/small-medium-business'), loadComponent: () => import('./pages/solutions/small-medium-business/small-medium-business').then(m => m.SmallMediumBusiness) },
          { path: 'professional-services', ...seo('solutions/professional-services'), loadComponent: () => import('./pages/solutions/professional-services/professional-services').then(m => m.ProfessionalServices) },
          { path: 'social-media-management', ...seo('solutions/social-media-management'), loadComponent: () => import('./pages/solutions/social-media-management/social-media-management').then(m => m.SocialMediaManagement) },
          { path: 'social-insights', ...seo('solutions/social-insights'), loadComponent: () => import('./pages/solutions/social-insights/social-insights').then(m => m.SocialInsights) },
          { path: 'brand-awareness', ...seo('solutions/brand-awareness'), loadComponent: () => import('./pages/solutions/brand-awareness/brand-awareness').then(m => m.BrandAwareness) },
          { path: 'industries', ...seo('solutions/industries'), loadComponent: () => import('./pages/solutions/industries/industries').then(m => m.Industries) },
        ]
      },
      {
        path: 'integrations',
        loadComponent: () => import('./pages/integration/integration.component').then(m => m.IntegrationComponent),
        children: [
          { path: '', ...seo('integrations'), loadComponent: () => import('./pages/integration/all-integrations/all-integrations').then(m => m.AllIntegrations) },
          { path: 'facebook', ...seo('integrations/facebook'), loadComponent: () => import('./pages/integration/facebook/facebook').then(m => m.FacebookIntegration) },
          { path: 'instagram', ...seo('integrations/instagram'), loadComponent: () => import('./pages/integration/instagram/instagram').then(m => m.InstagramIntegration) },
          { path: 'x', ...seo('integrations/x'), loadComponent: () => import('./pages/integration/x-twitter/x-twitter').then(m => m.XTwitterIntegration) },
          { path: 'linkedin', ...seo('integrations/linkedin'), loadComponent: () => import('./pages/integration/linkedin/linkedin').then(m => m.LinkedinIntegration) },
          { path: 'pinterest', ...seo('integrations/pinterest'), loadComponent: () => import('./pages/integration/pinterest/pinterest').then(m => m.PinterestIntegration) },
          { path: 'google-drive', ...seo('integrations/google-drive'), loadComponent: () => import('./pages/integration/google-drive/google-drive').then(m => m.GoogleDriveIntegration) },
          { path: 'dropbox', ...seo('integrations/dropbox'), loadComponent: () => import('./pages/integration/dropbox/dropbox').then(m => m.DropboxIntegration) },
          { path: 'threads', ...seo('integrations/threads'), loadComponent: () => import('./pages/integration/threads/threads').then(m => m.ThreadsIntegration) },
        ]
      },
      {
        path: 'demo',
        ...seo('demo'),
        loadComponent: () => import('./pages/schedule-demo/schedule-demo').then(m => m.ScheduleDemo)
      },
      {
        path: 'contact',
        ...seo('contact'),
        loadComponent: () => import('./pages/contact-us/index/index').then(m => m.Index)
      },
      {
        path: 'pricing',
        ...seo('pricing'),
        loadComponent: () => import('./pages/pricing/pricing').then(m => m.Pricing)
      },
      {
        path: 'podcast',
        ...seo('podcast'),
        loadComponent: () => import('./pages/podcast/podcast').then(m => m.Podcast)
      },
      {
        path: 'blogs',
        ...seo('blogs'),
        loadComponent: () => import('./pages/blogs/blogs').then(m => m.Blogs)
      },
      {
        // Detail page  meta comes from the record itself, set in the component.
        path: 'blogs/:id',
        loadComponent: () => import('./pages/blogs/blog-details/blog-details').then(m => m.BlogDetails)
      },
      {
        path: 'error',
        loadComponent: () => import('./pages/error/error.component').then(m => m.ErrorComponent),
        children: [
          { path: 'error404', ...seo('error/error404'), loadComponent: () => import('./pages/error/error404/error404').then(m => m.Error404) },
          { path: 'error500', ...seo('error/error500'), loadComponent: () => import('./pages/error/error500/error500').then(m => m.Error500) },
        ]
      }
    ]
  },
  {
    path: '**',
    redirectTo: 'error/error404',
    pathMatch: 'full'
  },
] as const;
