import { Routes } from '@angular/router';
import { seoResolver } from './core/resolvers/seo.resolver';

/** Every static page declares a `seoKey`; it maps to a page entry in super admin. */
const seo = (seoKey: string) => ({
  data: { seoKey },
  resolve: { seo: seoResolver },
});

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./layouts/main-layout/main-layout').then(m => m.MainLayout),
    children: [
      {
        path: '',
        ...seo('home'),
        loadComponent: () => import('./pages/home/index/index').then(m => m.Index)
      },
      {
        path: 'about',
        ...seo('about'),
        loadComponent: () => import('./pages/about-us/index/index').then(m => m.Index)
      },
      {
        path: 'team',
        ...seo('team'),
        loadComponent: () => import('./pages/team/index/index').then(m => m.Index)
      },
      {
        // The HTML sitemap for humans. The machine-readable one is the static
        // public/sitemap.xml, generated by scripts/generate-site-files.mjs.
        path: 'sitemap',
        ...seo('sitemap'),
        loadComponent: () => import('./pages/sitemap/sitemap').then(m => m.Sitemap)
      },
      {
        path: 'support',
        loadComponent: () => import('./pages/support/support.component').then(m => m.SupportComponent),
        children: [
          { path: '', ...seo('support'), loadComponent: () => import('./pages/support/support-center/support-center').then(m => m.SupportCenter) },
          { path: 'privacy-policy', ...seo('support/privacy-policy'), loadComponent: () => import('./pages/support/privacy-policy/privacy-policy').then(m => m.PrivacyPolicy) },
          { path: 'terms-of-service', ...seo('support/terms-of-service'), loadComponent: () => import('./pages/support/terms-of-service/terms-of-service').then(m => m.TermsOfService) },
          { path: 'cookie-policy', ...seo('support/cookie-policy'), loadComponent: () => import('./pages/support/cookie-policy/cookie-policy').then(m => m.CookiePolicy) },
          { path: 'website-terms', ...seo('support/website-terms'), loadComponent: () => import('./pages/support/website-terms/website-terms').then(m => m.WebsiteTerms) },
          { path: 'faq', ...seo('support/faq'), loadComponent: () => import('./pages/support/faq/faq').then(m => m.Faq) }
        ]
      },
      {
        path: 'company',
        loadComponent: () => import('./pages/company/company.component').then(m => m.CompanyComponent),
        children: [
          { path: '', redirectTo: 'careers', pathMatch: 'full' },
          { path: 'careers', ...seo('company/careers'), loadComponent: () => import('./pages/company/careers/careers').then(m => m.Careers) }
        ]
      },
      {
        path: 'contact',
        ...seo('contact'),
        loadComponent: () => import('./pages/contact-us/index/index').then(m => m.Index)
      },
      {
        path: 'blogs',
        ...seo('blogs'),
        loadComponent: () => import('./pages/blogs/blogs').then(m => m.Blogs)
      },
      {
        // Detail page  meta comes from the record itself, set in the component.
        path: 'blogs/:id',
        loadComponent: () => import('./pages/blogs/blog-details/blog-details').then(m => m.BlogDetails)
      },
      {
        path: 'error',
        loadComponent: () => import('./pages/error/error.component').then(m => m.ErrorComponent),
        children: [
          { path: 'error404', ...seo('error/error404'), loadComponent: () => import('./pages/error/error404/error404').then(m => m.Error404) },
          { path: 'error500', ...seo('error/error500'), loadComponent: () => import('./pages/error/error500/error500').then(m => m.Error500) },
        ]
      }
    ]
  },
  {
    path: '**',
    redirectTo: 'error/error404',
    pathMatch: 'full'
  },
] as const;
